server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Cấu hình này biến Promtail thành một trạm thu nhận log từ xa
  - job_name: syslog_from_ec2
    syslog:
      listen_address: 0.0.0.0:1514 # Promtail sẽ mở cổng này để "hứng" log từ EC2 bắn về
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "medical-api-ec2"
        host: "ec2-instance"

    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'instance'
